name: CI

on: [workflow_dispatch, push, pull_request]

jobs:
  test:
    name: 'Ruby: ${{ matrix.ruby-version }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.5', '2.6', '2.7', '3.0', 'jruby-9.1.17.0', 'jruby']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.MY_REPO_PAT }} # `GH_PAT` is a secret that contains your PAT
    - name: Checkout recog content
      uses: actions/checkout@v2
      with:
        path: recog-content
        repository: mkienow-r7/test-recog
        token: ${{ secrets.MY_REPO_PAT }} # `GH_PAT` is a secret that contains your PAT
#    - name: Copy recog content to code root for tests
#      #run: cp -R ./recog-content/xml .
#      run:  |
#        ls -lah
#        ls -lah ../
#        ls -lah ./recog-content
#        cp -R ./recog-content/xml .
    - name: Action debug output
      run: |
        echo "----------------------------------------------------------------------------------"
        ls -lah
        echo "----------------------------------------------------------------------------------"
        ls -lah ./test-recog/
        echo "----------------------------------------------------------------------------------"
        ls -lah ./recog-content
        echo "----------------------------------------------------------------------------------"
        ls -lah ../
        echo "----------------------------------------------------------------------------------"
        ls -lah ../../
        echo "----------------------------------------------------------------------------------"
        ls -lah /home/runner/work/test-recog-ruby/
        echo "----------------------------------------------------------------------------------"
        ls -lah /home/runner/work/test-recog-ruby/test-recog-ruby/
        echo "----------------------------------------------------------------------------------"
        ls -lah /home/runner/work/test-recog-ruby/test-recog-ruby/test-recog/
        echo "----------------------------------------------------------------------------------"
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: |
        echo "----------------------------------------------------------------------------------"
        ls -lah
        echo "----------------------------------------------------------------------------------"
        ls -lah ./test-recog/
        echo "----------------------------------------------------------------------------------"
        ls -lah ./recog-content
        echo "----------------------------------------------------------------------------------"
        ls -lah ../
        echo "----------------------------------------------------------------------------------"
        ls -lah ../../
        echo "----------------------------------------------------------------------------------"
        ls -lah /home/runner/work/test-recog-ruby/
        echo "----------------------------------------------------------------------------------"
        ls -lah /home/runner/work/test-recog-ruby/test-recog-ruby/
        echo "----------------------------------------------------------------------------------"
        ls -lah /home/runner/work/test-recog-ruby/test-recog-ruby/test-recog/
        echo "----------------------------------------------------------------------------------"
        bundle exec rake --version
        bundle exec rake tests
      env:
        JRUBY_OPTS: --server -J-Xms512m -J-Xmx2G